---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - ./config:/config
      - /data:/data
    ports:
      - 8787:8787
    restart: unless-stopped
