version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8080:8080
    volumes:
      - /data/files/filebrowser:/data
      - ./config:/config
    restart: always

